name: Playwright Tests
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Environment Variables
      run: |
        echo "REACT_APP_X_RAPID_API_KEY=${{ secrets.REACT_APP_X_RAPID_API_KEY }}" >> $GITHUB_ENV
        echo "REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }}" >> $GITHUB_ENV
        echo "REACT_APP_WEATHER_API_BASE_URL=https://madsakselsen.com/api/" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30